CMDB/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('assets.urls'))
]

assets/urls.py
from django.urls import path
from assets import views


app_name = 'assets'


urlpatterns = [
    path('report/', views.report, name='report'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('index/', views.index, name='index'),
    path('detail/<int:asset_id>/', views.detail, name='detail'),
    path('', views.dashboard),
]

assets/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Asset(models.Model):
    """所有资产的共有数据表"""

    asset_type_choice = (
        ('server', '服务器'),
        ('networkdevice', '网络设备'),
        ('storagedevice', '存储设备'),
        ('securitydevice', '安全设备'),
        ('software', '软件资产'),
    )

    asset_status = (
        (0, '在线'),
        (1, '下线'),
        (2, '未知'),
        (3, '故障'),
        (4, '备用'),
    )

    asset_type = models.CharField(choices=asset_type_choice, max_length=64, default='server', verbose_name='资产类型')
    name = models.CharField(max_length=64, unique=True, verbose_name='资产名称')  # 不可重复
    sn = models.CharField(max_length=128, unique=True, verbose_name='资产序列号')
    business_unit = models.ForeignKey('BusinessUnit', null=True, blank=True, verbose_name='所属业务线',
                                      on_delete=models.SET_NULL)

    status = models.SmallIntegerField(choices=asset_status, default=0, verbose_name='设备状态')

    manufacturer = models.ForeignKey('Manufacturer', null=True, blank=True, verbose_name='制造商',
                                     on_delete=models.SET_NULL)
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='管理IP')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='标签')
    admin = models.ForeignKey(User, null=True, blank=True, verbose_name='资产管理员', related_name='admin',
                              on_delete=models.SET_NULL)
    idc = models.ForeignKey('IDC', null=True, blank=True, verbose_name='所在机房', on_delete=models.SET_NULL)
    contract = models.ForeignKey('Contract', null=True, blank=True, verbose_name='合同', on_delete=models.SET_NULL)

    purchase_day = models.DateField(null=True, blank=True, verbose_name="购买日期")
    expire_day = models.DateField(null=True, blank=True, verbose_name="过保日期")
    price = models.FloatField(null=True, blank=True, verbose_name="价格")

    approved_by = models.ForeignKey(User, null=True, blank=True, verbose_name='批准人', related_name='approved_by',
                                    on_delete=models.SET_NULL)

    memo = models.TextField(null=True, blank=True, verbose_name='备注')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='批准日期')
    m_time = models.DateTimeField(auto_now=True, verbose_name='更新日期')

    def __str__(self):
        return '<%s>  %s' % (self.get_asset_type_display(), self.name)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"
        ordering = ['-c_time']


class Server(models.Model):
    """服务器设备"""

    sub_asset_type_choice = (
        (0, 'PC服务器'),
        (1, '刀片机'),
        (2, '小型机'),
    )

    created_by_choice = (
        ('auto', '自动添加'),
        ('manual', '手工录入'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)  # 非常关键的一对一关联！asset被删除的时候一并删除server
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="服务器类型")
    created_by = models.CharField(choices=created_by_choice, max_length=32, default='auto', verbose_name="添加方式")
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server',
                                  blank=True, null=True, verbose_name="宿主机", on_delete=models.CASCADE)  # 虚拟机专用字段
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name='服务器型号')
    raid_type = models.CharField(max_length=512, blank=True, null=True, verbose_name='Raid类型')

    os_type = models.CharField('操作系统类型', max_length=64, blank=True, null=True)
    os_distribution = models.CharField('发行商', max_length=64, blank=True, null=True)
    os_release = models.CharField('操作系统版本', max_length=64, blank=True, null=True)

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = "服务器"


class SecurityDevice(models.Model):
    """安全设备"""

    sub_asset_type_choice = (
        (0, '防火墙'),
        (1, '入侵检测设备'),
        (2, '互联网网关'),
        (4, '运维审计系统'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="安全设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='安全设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '安全设备'
        verbose_name_plural = "安全设备"


class StorageDevice(models.Model):
    """存储设备"""

    sub_asset_type_choice = (
        (0, '磁盘阵列'),
        (1, '网络存储器'),
        (2, '磁带库'),
        (4, '磁带机'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="存储设备类型")
    model = models.CharField(max_length=128, default='未知型号', verbose_name='存储设备型号')

    def __str__(self):
        return self.asset.name + "--" + self.get_sub_asset_type_display() + str(self.model) + " id:%s" % self.id

    class Meta:
        verbose_name = '存储设备'
        verbose_name_plural = "存储设备"


class NetworkDevice(models.Model):
    """网络设备"""

    sub_asset_type_choice = (
        (0, '路由器'),
        (1, '交换机'),
        (2, '负载均衡'),
        (4, 'VPN设备'),
    )

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="网络设备类型")

    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="VLanIP")
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name="内网IP")

    model = models.CharField(max_length=128, default='未知型号',  verbose_name="网络设备型号")
    firmware = models.CharField(max_length=128, blank=True, null=True, verbose_name="设备固件版本")
    port_num = models.SmallIntegerField(null=True, blank=True, verbose_name="端口个数")
    device_detail = models.TextField(null=True, blank=True, verbose_name="详细配置")

    def __str__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = "网络设备"


class Software(models.Model):
    """
    只保存付费购买的软件
    """
    sub_asset_type_choice = (
        (0, '操作系统'),
        (1, '办公\开发软件'),
        (2, '业务软件'),
    )

    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0, verbose_name="软件类型")
    license_num = models.IntegerField(default=1, verbose_name="授权数量")
    version = models.CharField(max_length=64, unique=True, help_text='例如: RedHat release 7 (Final)',
                               verbose_name='软件/系统版本')

    def __str__(self):
        return '%s--%s' % (self.get_sub_asset_type_display(), self.version)

    class Meta:
        verbose_name = '软件/系统'
        verbose_name_plural = "软件/系统"


class IDC(models.Model):
    """机房"""
    name = models.CharField(max_length=64, unique=True, verbose_name="机房名称")
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name='备注')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机房'
        verbose_name_plural = "机房"


class Manufacturer(models.Model):
    """厂商"""

    name = models.CharField('厂商名称', max_length=64, unique=True)
    telephone = models.CharField('支持电话', max_length=30, blank=True, null=True)
    memo = models.CharField('备注', max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '厂商'
        verbose_name_plural = "厂商"


class BusinessUnit(models.Model):
    """业务线"""

    parent_unit = models.ForeignKey('self', blank=True, null=True, related_name='parent_level',
                                    on_delete=models.SET_NULL)
    name = models.CharField('业务线', max_length=64, unique=True)
    memo = models.CharField('备注', max_length=64, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '业务线'
        verbose_name_plural = "业务线"


class Contract(models.Model):
    """合同"""

    sn = models.CharField('合同号', max_length=128, unique=True)
    name = models.CharField('合同名称', max_length=64)
    memo = models.TextField('备注', blank=True, null=True)
    price = models.IntegerField('合同金额')
    detail = models.TextField('合同详细', blank=True, null=True)
    start_day = models.DateField('开始日期', blank=True, null=True)
    end_day = models.DateField('失效日期', blank=True, null=True)
    license_num = models.IntegerField('license数量', blank=True, null=True)
    c_day = models.DateField('创建日期', auto_now_add=True)
    m_day = models.DateField('修改日期', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '合同'
        verbose_name_plural = "合同"


class Tag(models.Model):
    """标签"""
    name = models.CharField('标签名', max_length=32, unique=True)
    c_day = models.DateField('创建日期', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = "标签"


class CPU(models.Model):
    """CPU组件"""

    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)  # 设备上的cpu肯定都是一样的，所以不需要建立多个cpu数据，一条就可以，因此使用一对一。
    cpu_model = models.CharField('CPU型号', max_length=128, blank=True, null=True)
    cpu_count = models.PositiveSmallIntegerField('物理CPU个数', default=1)
    cpu_core_count = models.PositiveSmallIntegerField('CPU核数', default=1)

    def __str__(self):
        return self.asset.name + ":   " + self.cpu_model

    class Meta:
        verbose_name = 'CPU'
        verbose_name_plural = "CPU"


class RAM(models.Model):
    """内存组件"""

    asset = models.ForeignKey('Asset', on_delete=models.CASCADE)

assets/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
import json
from assets import models
from assets import asset_handler
from django.shortcuts import get_object_or_404


def index(request):
    """
    资产总表视图
    :param request:
    :return:
    """
    assets = models.Asset.objects.all()
    return render(request, 'assets/index.html', locals())


def dashboard(request):
    total = models.Asset.objects.count()
    upline = models.Asset.objects.filter(status=0).count()
    offline = models.Asset.objects.filter(status=1).count()
    unknown = models.Asset.objects.filter(status=2).count()
    breakdown = models.Asset.objects.filter(status=3).count()
    backup = models.Asset.objects.filter(status=4).count()

    up_rate = round(upline/total*100)
    o_rate = round(offline / total * 100)
    un_rate = round(unknown / total * 100)
    bd_rate = round(breakdown / total * 100)
    bu_rate = round(backup / total * 100)

    server_number = models.Server.objects.count()
    networkdevice_number = models.NetworkDevice.objects.count()
    storagedevice_number = models.StorageDevice.objects.count()
    securitydevice_number = models.SecurityDevice.objects.count()
    software_number = models.Software.objects.count()

    return render(request, 'assets/dashboard.html', locals())


def detail(request, asset_id):
    """
    以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。
    :param request:
    :param asset_id:
    :return:
    """

    asset = get_object_or_404(models.Asset, id=asset_id)
    return render(request, 'assets/detail.html', locals())





@csrf_exempt
def report(request):
    if request.method == 'POST':
        asset_data = request.POST.get('asset_data')
        data = json.loads(asset_data)
        if not data:
            return HttpResponse('没有数据！')
        if not issubclass(dict, type(data)):
            return HttpResponse('数据必须为字典格式！')
        # 你的检测代码

        sn = data.get('sn', None)

        if sn:
            asset_obj = models.Asset.objects.filter(sn=sn)  # [obj]
            if asset_obj:
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse('资产数据已经更新。')
            else:
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse('没有资产sn，请检查数据内容！')

    return HttpResponse('200 ok')

assets/templates/assets/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}资产详细{% endblock %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产详细
        <small>asset info</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>资产总表</li>
        <li class="active">资产详细</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

     <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">

        <div class="box-header with-border">
            <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">资产：{{ asset.name }}</strong></h3>

            <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
            </div>
        </div>

        <div class="box-body">

            <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>制造商</th>
                        <th>管理IP</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_asset_type_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td>{{ asset.business_unit|default:'N/A' }}</td>
                    <td>{{ asset.manufacturer|default:'N/A' }}</td>
                    <td>{{ asset.manage_ip|default:'N/A' }}</td>
                    <td>{{ asset.idc|default:'N/A' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <br />
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                    <tr>
                        <th>合同</th>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.contract.name|default:'N/A' }}</td>
                    <td>{{ asset.price|default:'N/A' }}</td>
                    <td>{{ asset.purchase_day|default:'N/A' }}</td>
                    <td>{{ asset.expire_day|default:'N/A' }}</td>
                    <td>{{ asset.admin|default:'N/A' }}</td>
                    <td>{{ asset.approved_by|default:'N/A' }}</td>
                    <td>{{ asset.memo|default:'N/A' }}</td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>服务器:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>型号</th>
                        <th>宿主机</th>
                        <th>Raid类型</th>
                        <th>OS类型</th>
                        <th>OS发行版本</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.server.get_sub_asset_type_display }}</td>
                    <td>{{ asset.server.model|default:'N/A' }}</td>
                    <td>{{ asset.server.hosted_on.id|default:'N/A' }}</td>
                    <td>{{ asset.server.raid_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_distribution|default:'N/A' }}</td>
                    <td>{{ asset.server.os_release|default:'N/A' }}</td>
                    <td>{{ asset.server.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>CPU:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid purple;border-bottom:1px solid purple">
                <thead>
                    <tr>
                        <th  style="width: 45%">CPU型号</th>
                        <th  style="width: 15%">物理CPU个数</th>
                        <th>CPU核数</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.cpu.cpu_model|default:'N/A' }}</td>
                    <td>{{ asset.cpu.cpu_count|default:'1' }}</td>
                    <td>{{ asset.cpu.cpu_core_count|default:'1' }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>内存:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid orangered;border-bottom:1px solid orangered">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for ram in asset.ram_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ ram.model|default:'N/A' }}</td>
                        <td>{{ ram.capacity|default:'N/A' }}</td>
                        <td>{{ ram.slot }}</td>
                        <td>{{ ram.manufacturer|default:'N/A' }}</td>
                        <td>{{ ram.sn|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <h4><b>硬盘:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid brown;border-bottom:1px solid brown">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>接口类型</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for disk in asset.disk_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ disk.model|default:'N/A' }}</td>
                        <td>{{ disk.capacity|default:'N/A' }}</td>
                        <td>{{ disk.slot|default:'N/A'  }}</td>
                        <td>{{ disk.get_interface_type_display }}</td>
                        <td>{{ disk.manufacturer|default:'N/A' }}</td>
                        <td>{{ disk.sn}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <h4><b>网卡:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid #a59b1a;border-bottom:1px solid #a59b1a">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>名称</th>
                        <th>型号</th>
                        <th>MAC</th>
                        <th>IP</th>
                        <th>掩码</th>
                        <th>绑定地址</th>
                    </tr>
                </thead>
                <tbody>
                {% for nic in asset.nic_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ nic.name|default:'N/A' }}</td>
                        <td>{{ nic.model }}</td>
                        <td>{{ nic.mac  }}</td>
                        <td>{{ nic.ip_address|default:'N/A' }}</td>
                        <td>{{ nic.net_mask|default:'N/A' }}</td>
                        <td>{{ nic.bonding|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- /.box-body -->



        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assets:index' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->


{% endblock %}

{% block script %}

{% endblock %}

assets/templates/assets/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}资产总表{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产总表
        <small>assets list</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">资产总表</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
          <h3 class="box-title">资产总表<small>(不含软件)</small></h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <table id="assets_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>资产类型</th>
                        <th>子类型</th>
                        <th>资产名称</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>状态</th>
                        <th>机房</th>
                        <th>更新日期</th>
                        <th>标签</th>
                    </tr>
                </thead>
                <tbody>

                {% for asset in assets %}

                    <tr>
                        <td>{{ forloop.counter }}</td>

                        {% if asset.asset_type == 'server' %}
                          <td class="text-green text-bold">{{ asset.get_asset_type_display }}</td>
                          <td>{{ asset.server.get_sub_asset_type_display }}</td>
                        {% elif asset.asset_type == "networkdevice" %}
                          <td class="text-yellow text-bold">{{ asset.get_asset_type_display }}</td>
                          <td>{{ asset.networkdevice.get_sub_asset_type_display }}</td>
                        {% elif asset.asset_type == "storagedevice" %}
                          <td class="text-blue text-bold">{{ asset.get_asset_type_display }}</td>
                          <td>{{ asset.storagedevice.get_sub_asset_type_display }}</td>
                        {% elif asset.asset_type == "securitydevice" %}
                          <td class="text-red text-bold">{{ asset.get_asset_type_display }}</td>
                          <td>{{ asset.securitydevice.get_sub_asset_type_display }}</td>
                        {% endif %}

                        {% if asset.asset_type == 'server' %}
                            <td><a href="{% url 'assets:detail' asset.id %}">{{ asset.name }}</a></td>
                        {% else %}
                            <td>{{ asset.name }}</td>
                        {% endif %}

                        <td>{{ asset.sn }}</td>

                        <td>{{ asset.business_unit|default_if_none:"-" }}</td>

                        {% if asset.status == 0 %}
                          <td><label class="label label-success">{{ asset.get_status_display }}</label></td>
                        {% elif asset.status == 1 %}
                          <td><label class="label label-warning">{{ asset.get_status_display }}</label></td>
                        {% elif asset.status == 2 %}
                          <td><label class="label label-default">{{ asset.get_status_display }}</label></td>
                        {% elif asset.status == 3 %}
                          <td><label class="label label-danger">{{ asset.get_status_display }}</label></td>
                        {% elif asset.status == 4 %}
                          <td><label class="label label-info">{{ asset.get_status_display }}</label></td>
                        {% endif %}

                        <td>{{ asset.idc|default:"-" }}</td>

                        <td>{{ asset.m_time|date:"Y/m/d [H:m:s]" }}</td>

                        <td>
                          {% for tag in asset.tags.all %}
                            <label class="label label-primary">{{ tag.name }}</label>
                            {% empty %}
                              -
                            {% endfor %}
                        </td>
                    </tr>

                {% empty %}
                <tr>没有数据</tr>
                {% endfor %}

                </tbody>
                <tfoot>
                    <tr>
                        <th>序号</th>
                        <th>资产类型</th>
                        <th>子类型</th>
                        <th>资产名称</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>状态</th>
                        <th>机房</th>
                        <th>更新日期</th>
                        <th>标签</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

<script>

$(function () {
        $('#assets_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>

{% endblock %}